
development:
  adapter: postgresql
  encoding: unicode
  database: ruby_quest
  pool: 5
  username: MTen
  password:
  
test:
  adapter: postgresql
  encoding: unicode
  database: ruby_quest
  pool: 5
  username: MTen
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: ruby_quest
  pool: 5
  username: MTen
  password:

